- name: DEPLOY AS3
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST
  vars_files:
    - ../creds/big_creds.yaml

  tasks:
    - name: Execute declaration
      uri:
        url: https://18.130.90.35/mgmt/shared/appsvcs/declare/
        method: "{{uri_method}}"
        user: "{{bigip_user}}"
        password: "{{bigip_pass}}"
        body: "{{ lookup('file','./simple-as3.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no

